[KARAF-7580] Prevent StringIndexOutOfBoundsException on help with newlines
Avoids
java.lang.StringIndexOutOfBoundsException: index -1, length 0
    at java.lang.String.checkIndex(String.java:4563) ~[?:?]
    at java.lang.AbstractStringBuilder.charAt(AbstractStringBuilder.java:351) ~[?:?]
    at java.lang.StringBuilder.charAt(StringBuilder.java:91) ~[?:?]
    at org.apache.karaf.shell.support.table.Row.getContent(Row.java:84) ~[?:?]
    at org.apache.karaf.shell.support.table.ShellTable.print(ShellTable.java:151) ~[?:?]
    at org.apache.karaf.shell.support.table.ShellTable.print(ShellTable.java:111) ~[?:?]
    at org.apache.karaf.shell.impl.console.commands.help.CommandListHelpProvider.printMethodList(CommandListHelpProvider.java:167) ~[?:?]

(cherry picked from commit e99eb51a5127093933d81164e7fbea75c22f380a)