[KARAF-3764] NoClassDefFoundError when the features-core bundle is refreshed by itself
Also fix problems with eventadmin and packageadmin causing refreshes of pax-logging-api and most of bundles at the start phase